[package]
name = "et-mm-bot"
version = "0.0.1"
authors = ["keith miller <keith.miller@thermosystems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
